service_name: 'ai-llm-agent'
llm_source: 'local'
endpoint_url: "https://ai-model-{APP_ENV}.jubo.health/api/v1/ai-llm-agent-model"
max_new_tokens: 512
temperature: 0.2
top_k: 50
top_p: 0.95
repetition_penalty: 1.05
huggingfacehub_api_token: "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"
